code --install-extension aaron-bond.better-comments
code --install-extension aliariff.vscode-erb-beautify
code --install-extension angular.ng-template
code --install-extension batisteo.vscode-django
code --install-extension castwide.solargraph
code --install-extension christian-kohler.path-intellisense
code --install-extension eservice-online.vs-sharper
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension github.github-vscode-theme
code --install-extension jesschadwick.nuget-reverse-package-search
code --install-extension jinxdash.prettier-rust
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension josephwoodward.vscodeilviewer
code --install-extension k--kato.docomment
code --install-extension matepek.vscode-catch2-test-adapter
code --install-extension mechatroner.rainbow-csv
code --install-extension mgesbert.python-path
code --install-extension mikestead.dotenv
code --install-extension mosapride.zenkaku
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.flake8
code --install-extension ms-python.isort
code --install-extension ms-python.mypy-type-checker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension oderwat.indent-rainbow
code --install-extension oracle.oracle-java
code --install-extension patcx.vscode-nuget-gallery
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension shardulm94.trailing-spaces
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vadimcn.vscode-lldb
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscode-icons-team.vscode-icons